### ISSUE TITLE
Can't access Google drive from China because of the GFW.

### ISSUE THREAD

**Issue by lucasjinreal** [r4ghu/iOS-CoreML-Yolo#1]
This is not an issue, but may I ask to get the TinyYOLOv1.mlmodel, I am in China, the god damn it GFW avoid me from access Google, so can you give me another link please? That would be many many thanks if I can have a accessable download link of that TinyYOLOv1.mlmodel model!!!

**Comment by lucasjinreal** [comment]
By the way, as the Theano are not being maintained anymore, Keras should more likely using TensorFlow as backend, what did you see?

**Comment by lyxlty** [comment]
@r4ghu  hi! I have got yolov3ml.model(darknet convert keras ,keras convert yolov3ml.model),i use coremltools predict a image,coremltools predict have 3 output (3 different scal feature map) then but I do not know how to get anchors and  how to nms for anchors ,
 thanks
