### ISSUE TITLE
the convert pipeline is broken

### ISSUE THREAD

**Issue by mingmmq** [r4ghu/iOS-CoreML-Yolo#2]
seem the coremltools is not imported, after imported below error happens

```
Traceback (most recent call last):
  File "convert.py", line 133, in <module>
    coreml_model_p1p2p3 = coremltools.converters.keras.convert(model_p1p2p3,
AttributeError: 'module' object has no attribute 'convert'
```

**Comment by mingmmq** [comment]
Could you please upload the "mlmodel" file for this project?

**Comment by haemi** [comment]
would love the mlmodel as well

**Comment by cornr** [comment]
Thanks for your awesome post. Now I would also like to try out your app but I don't even know how to import the coremltools 😄 

    File "convert.py", line 132, in <module>
    coreml_model_p1p2p3 = coremltools.converters.keras.convert(model_p1p2p3,
    NameError: name 'coremltools' is not defined`

**Comment by ykguler** [comment]
Same problem..

**Comment by r4ghu** [comment]
The bug in `convert.py` has been resolved. Thanks for notifying this!
