### ISSUE TITLE
doesn't detect anything

### ISSUE THREAD

**Issue by anonym24** [r4ghu/iOS-CoreML-Yolo#4]
Orientation, Camera are weird on my iPad

it's always conversely rotation with any iPad position in my hands

also weird zoom, objects on the camera are closer than should be

p.s. I also don't get any detected objects (drawn rectangles), mb it's because of the wrong frames orientation and yolo just doesn't detect anything

...

fixed zoom with setting
        session.sessionPreset = AVCaptureSessionPresetPhoto, iPad just isn't 16:9

**Comment by anonym24** [comment]
actually seems camera ok if turn my iPad in Portrait orientation, but still it doesn't detect anything

**Comment by anonym24** [comment]
![screenshot at jan 30 10-59-07](https://user-images.githubusercontent.com/8851301/35557048-a349bf3a-05ac-11e8-881c-3eabba68beca.png)

**Comment by r4ghu** [comment]
The project should work fine on iPad, may be you should update the layout that works for the latest iOS version
