### ISSUE TITLE
How to create our own images weights rather than pre-trained weights

### ISSUE THREAD

**Issue by UHemarajU** [r4ghu/iOS-CoreML-Yolo#5]
Hi r4ghu,

I want to create a custom object detection model using Yolo. In your tutorial i found that the pre trained weights. But can you tell me how to create our own images weights.

Thanks in Advance.

**Comment by r4ghu** [comment]
You can try checking the Tensorflow's Object Detection Pipeline. It has resources to train models on your custom data.
