### ISSUE TITLE
Explanation for loading weights

### ISSUE THREAD

**Issue by HarshdeepGupta** [r4ghu/iOS-CoreML-Yolo#7]
In the `load_weights` function, there is this line, which ignores the first few values of the loaded weights:

`data = data[4:]`

Can you please explain why we are doing so? And why is this even working?

**Comment by r4ghu** [comment]
This function has been taken from - https://github.com/xslittlegrass/CarND-Vehicle-Detection/blob/master/utils/utils.py . I have cited this repo in my blog too. For any questions related to this function, you can ask in that repo. I am closing this thread for now. Please feel free to re-open the same thread for any future questions.
